/**
 * SiteBundle — the portable export/import format for a complete site snapshot.
 *
 * A bundle contains:
 *   - optionally: the site shell (breakpoints, settings, classes, files, runtime config)
 *   - all (or selected) data tables
 *   - all (or selected) data rows
 *   - optionally: non-deleted media assets with bytes embedded as base64
 *
 * The bundle is intended for self-contained transfer between self-hosted instances.
 * Media bytes are embedded directly in the JSON (base64-encoded). For large sites
 * this produces a large JSON file; the caller should handle streaming or chunking
 * at the transport layer. v1 caveat: bundles are assembled in memory.
 *
 * Import side supports three strategies:
 *   - replace         — wipe everything, reimport from bundle (destructive)
 *   - merge-add       — insert rows/tables that don't exist; skip those that do
 *   - merge-overwrite — upsert rows/tables; overwrite existing content with bundle
 *
 * Variants are NOT included in media exports. They are regenerated by the upload
 * pipeline on first request after import.
 */

import { Type, type Static } from '@core/utils/typeboxHelpers'
import { DataTableSchema, DataRowSchema, DataTableKindSchema } from './schemas'
import { SiteShellSchema } from '@core/page-tree'

// ---------------------------------------------------------------------------
// MediaAssetExport
// ---------------------------------------------------------------------------

/**
 * A media asset record serialized for bundle transfer. `bytesBase64` holds the
 * raw file bytes encoded as Base64. `storagePath` is the relative path inside
 * the uploads directory so the import handler can write the file and reconstruct
 * `publicPath` as `/uploads/<storagePath>`.
 *
 * Variants, folder memberships, and deleted/replaced timestamps are intentionally
 * omitted — they either regenerate automatically or are not needed on a fresh import.
 */
/**
 * A safe relative path: no leading slash and no `..` path segment. Other
 * characters (spaces, parens, unicode) are allowed since media filenames are
 * arbitrary — the only goal is to forbid traversal/absolute escapes.
 */
const SAFE_RELATIVE_PATH_PATTERN = '^(?!/)(?!.*(?:^|/)\\.\\.(?:$|/)).+$'

export const MediaAssetExportSchema = Type.Object({
  id: Type.String(),
  filename: Type.String(),
  mimeType: Type.String(),
  sizeBytes: Type.Number(),
  altText: Type.String(),
  caption: Type.String(),
  title: Type.String(),
  tags: Type.Array(Type.String()),
  width: Type.Union([Type.Number(), Type.Null()]),
  height: Type.Union([Type.Number(), Type.Null()]),
  durationMs: Type.Union([Type.Number(), Type.Null()]),
  dominantColor: Type.Union([Type.String(), Type.Null()]),
  blurHash: Type.Union([Type.String(), Type.Null()]),
  /**
   * Relative path inside the uploads directory, e.g. `"abc123-photo.jpg"`.
   * Must not start with `/` or contain a `..` segment — the import handler
   * writes file bytes to `join(uploadsDir, storagePath)`, so traversal here is
   * an arbitrary-file-write primitive (ISS-009). The sink re-asserts
   * containment via `assertPathWithin`; this is the boundary guard.
   */
  storagePath: Type.String({ pattern: SAFE_RELATIVE_PATH_PATTERN }),
  /** Video poster image path (relative to uploads dir), or null for non-video assets. */
  posterPath: Type.Union([Type.String({ pattern: SAFE_RELATIVE_PATH_PATTERN }), Type.Null()]),
  /** Raw file bytes encoded as Base64. */
  bytesBase64: Type.String(),
})

// ---------------------------------------------------------------------------
// ImportStrategy
// ---------------------------------------------------------------------------

/**
 * Controls how an import merges the bundle with the local site state.
 *
 *   replace         — delete everything, reimport from bundle (destructive)
 *   merge-add       — only add what's missing; never overwrite existing content
 *   merge-overwrite — upsert: add missing, update existing with bundle values
 */
export const ImportStrategySchema = Type.Union([
  Type.Literal('replace'),
  Type.Literal('merge-add'),
  Type.Literal('merge-overwrite'),
])

export type ImportStrategy = Static<typeof ImportStrategySchema>

// ---------------------------------------------------------------------------
// ExportRequest
// ---------------------------------------------------------------------------

/**
 * Request body accepted by `POST /admin/api/cms/export` (and query string
 * equivalent for `GET`). All fields are optional — omitting them produces the
 * same full-site export as the v1 single-button behavior.
 */
export const ExportRequestSchema = Type.Object({
  /** Restrict export to these table ids. If omitted, all tables are included. */
  tables: Type.Optional(Type.Array(Type.String())),
  /** Restrict rows to these specific row ids. If omitted, all rows in the
   *  selected tables are included. */
  rowIds: Type.Optional(Type.Array(Type.String())),
  /** Embed media asset bytes in the bundle (increases bundle size). Default false. */
  includeMedia: Type.Optional(Type.Boolean()),
  /** Include the site shell (breakpoints, settings, classes, files, runtime).
   *  Default true. Set to false for content-only exports. */
  includeSite: Type.Optional(Type.Boolean()),
})

export type ExportRequest = Static<typeof ExportRequestSchema>

// ---------------------------------------------------------------------------
// BundlePreview
// ---------------------------------------------------------------------------

/**
 * Per-table diff entry returned by the preview endpoint. Describes what the
 * import would do to this table under the `replace` or `merge-*` strategies.
 */
const BundlePreviewTableEntrySchema = Type.Object({
  id: Type.String(),
  name: Type.String(),
  kind: DataTableKindSchema,
  /** Number of rows in the bundle for this table. */
  inBundle: Type.Number(),
  /** Rows in the bundle whose id already exists locally (would be overwritten by merge-overwrite). */
  willReplace: Type.Number(),
  /** Rows in the bundle whose id does not exist locally (new rows). */
  willAdd: Type.Number(),
  /** Current number of non-deleted rows in this table on the local instance. */
  currentLocal: Type.Number(),
})

/**
 * Read-only diff returned by `POST /admin/api/cms/import/preview`.
 * Shows the operator what would happen before they commit an import.
 */
export const BundlePreviewSchema = Type.Object({
  meta: Type.Object({
    exportedAt: Type.String(),
    sourceSiteName: Type.Union([Type.String(), Type.Null()]),
    schemaVersion: Type.Literal(1),
  }),
  tables: Type.Array(BundlePreviewTableEntrySchema),
  totals: Type.Object({
    rows: Type.Number(),
    mediaFiles: Type.Number(),
    mediaEmbedded: Type.Boolean(),
  }),
})

export type BundlePreview = Static<typeof BundlePreviewSchema>

// ---------------------------------------------------------------------------
// ImportResult
// ---------------------------------------------------------------------------

/**
 * Success response returned by `POST /admin/api/cms/import`.
 * Counters describe what actually happened, broken down by strategy semantics.
 */
export const ImportResultSchema = Type.Object({
  ok: Type.Literal(true),
  strategy: ImportStrategySchema,
  tablesAffected: Type.Number(),
  rowsInserted: Type.Number(),
  rowsReplaced: Type.Number(),
  rowsSkipped: Type.Number(),
  mediaImported: Type.Number(),
})

export type ImportResult = Static<typeof ImportResultSchema>

// ---------------------------------------------------------------------------
// SiteBundle
// ---------------------------------------------------------------------------

export const SiteBundleSchema = Type.Object({
  /** Schema version for forward-compat checks. Always 1 for this format. */
  schemaVersion: Type.Literal(1),
  /** ISO 8601 datetime string recording when the bundle was created. */
  exportedAt: Type.String(),
  /** Human-readable name of the site that produced this bundle. */
  sourceSiteName: Type.Optional(Type.String()),
  /**
   * The lean site shell: breakpoints, settings, classes, files, runtime.
   * Optional — omitted for content-only exports (`includeSite: false`).
   * Does NOT include pages or visual components — those are in `rows`.
   */
  site: Type.Optional(SiteShellSchema),
  /** All (or selected) data tables including system tables. */
  tables: Type.Array(DataTableSchema),
  /** All (or selected) non-deleted data rows. */
  rows: Type.Array(DataRowSchema),
  /** Non-deleted media assets with embedded bytes (optional — may be omitted to keep bundle small). */
  media: Type.Optional(Type.Array(MediaAssetExportSchema)),
})

export type SiteBundle = Static<typeof SiteBundleSchema>
