/**
 * Subtree snapshots — the shared capture/restore engine behind the editor
 * clipboard (copy/cut/paste) and saved layouts (save-as-layout/insert).
 *
 * A snapshot is a self-contained `{ nodes, classes }` pair: the flat node map
 * of one or more captured subtrees plus every style rule those nodes
 * referenced at capture time. Restoring a snapshot mints fresh node ids and
 * runs the class plan below, so both paste and layout insertion behave
 * identically — one engine, two front doors.
 *
 * Class restore rules (shared contract):
 * - Framework classes (`framework:*`) are matched by NAME against the target
 *   site's class registry; if no match exists, the classId is dropped.
 *   Framework classes are deterministically generated by the active document,
 *   so importing stale generated definitions would pollute it.
 * - Scoped (module-style) classes are always cloned with a fresh ID and the
 *   `scope.nodeId` remapped to the new node ID; scopes referencing nodes
 *   outside the captured subtree are dropped.
 * - All other (regular) classes are imported into the target site preserving
 *   their original ID. Same-ID classes already in the target are reused.
 */

import { nanoid } from 'nanoid'
import type { NodeTree, PageNode, SiteDocument, StyleRule } from '@core/page-tree'
import { buildSubtreeNodeIdMap, pasteSubtree } from '@core/page-tree'
import type { InsertLocation } from '@site/store/insertLocation'

/** A captured set of subtrees plus the classes they reference. */
interface SubtreeSnapshot {
  /** Ordered root node ids inside `nodes`. */
  rootNodeIds: string[]
  /** Flat map of every node in every captured subtree. */
  nodes: Record<string, PageNode>
  /** Style rules referenced by any captured node. */
  classes: Record<string, StyleRule>
}

/**
 * Collect the subtrees rooted at every id in `rootIds` into a single flat
 * nodes map. Skips ids not present in the tree (returning a non-null result as
 * long as at least one root resolved). Node and children arrays are copied so
 * the snapshot is detached from the live tree.
 */
export function collectSubtreeNodes(
  tree: NodeTree<PageNode>,
  rootIds: string[],
): { rootNodeIds: string[]; nodes: Record<string, PageNode> } | null {
  if (rootIds.length === 0) return null
  const nodes: Record<string, PageNode> = {}
  const validRoots: string[] = []
  for (const rootId of rootIds) {
    if (!tree.nodes[rootId]) continue
    validRoots.push(rootId)
    const stack = [rootId]
    while (stack.length > 0) {
      const id = stack.pop()!
      if (nodes[id]) continue
      const node = tree.nodes[id]
      if (!node) continue
      nodes[id] = { ...node, children: [...node.children] }
      stack.push(...node.children)
    }
  }
  if (validRoots.length === 0) return null
  return { rootNodeIds: validRoots, nodes }
}

/**
 * Collect every class referenced anywhere in the captured nodes from
 * `siteClasses`. Missing classes (e.g. dangling classIds) are silently
 * skipped — the restore step also filters dangling references via the
 * classIdRemap.
 */
export function collectReferencedClasses(
  nodes: Record<string, PageNode>,
  siteClasses: Record<string, StyleRule>,
): Record<string, StyleRule> {
  const classes: Record<string, StyleRule> = {}
  for (const node of Object.values(nodes)) {
    for (const classId of node.classIds) {
      if (classes[classId]) continue
      const cls = siteClasses[classId]
      if (cls) classes[classId] = cls
    }
  }
  return classes
}

const FRAMEWORK_ID_PREFIX = 'framework:'

/**
 * Restore a snapshot into `tree` at `location`, materialising restored classes
 * into `site.styleRules`. Both `tree` and `site` are expected to be Mutative
 * drafts inside one store transaction, so the node paste and the class writes
 * land in a single undo step.
 *
 * Every root is placed consecutively at the resolved location in snapshot
 * order. Returns the new root node ids (snapshot order).
 *
 * Callers own the policy guards (e.g. the one-outlet-per-document invariant) —
 * this function only performs the mechanical restore.
 */
export function insertSnapshotSubtrees(
  tree: NodeTree<PageNode>,
  site: SiteDocument,
  snapshot: SubtreeSnapshot,
  location: InsertLocation,
): string[] {
  // Pre-compute new node IDs across ALL roots so scoped-class scope.nodeId
  // can be remapped before classes are written into the target site.
  // Each root's subtree gets its own id-remap; we union them into one map
  // so a class scoped to any restored node finds its remap.
  const nodeIdMap = new Map<string, string>()
  for (const rootId of snapshot.rootNodeIds) {
    const subtreeMap = buildSubtreeNodeIdMap(rootId, snapshot.nodes)
    for (const [oldId, newId] of subtreeMap) {
      if (!nodeIdMap.has(oldId)) nodeIdMap.set(oldId, newId)
    }
  }

  // Build the class plan. Each entry resolves to one of:
  //   - { kind: 'reuse', id }   — already present in target site
  //   - { kind: 'add', cls }    — write `cls` to site.styleRules (id may differ)
  //   - { kind: 'drop' }        — strip from restored classIds
  type ClassPlan =
    | { kind: 'reuse'; id: string }
    | { kind: 'add'; id: string; cls: StyleRule }
    | { kind: 'drop' }

  const now = Date.now()
  const targetClasses = site.styleRules
  const plans = new Map<string, ClassPlan>()

  // Build a name → id index for framework classes in the active document
  // (used to match regenerated framework references that may have a
  // different id than the snapshot).
  const frameworkByName = new Map<string, string>()
  for (const [id, cls] of Object.entries(targetClasses)) {
    if (id.startsWith(FRAMEWORK_ID_PREFIX)) frameworkByName.set(cls.name, id)
  }

  for (const [classId, cls] of Object.entries(snapshot.classes)) {
    if (cls.scope?.type === 'node') {
      // Scoped class — always cloned with a fresh id, scope.nodeId remapped.
      const newScopeNodeId = nodeIdMap.get(cls.scope.nodeId)
      if (!newScopeNodeId) {
        plans.set(classId, { kind: 'drop' })
        continue
      }
      const newId = nanoid()
      plans.set(classId, {
        kind: 'add',
        id: newId,
        cls: {
          ...cls,
          id: newId,
          scope: { ...cls.scope, nodeId: newScopeNodeId },
          styles: { ...cls.styles },
          contextStyles: Object.fromEntries(
            Object.entries(cls.contextStyles).map(([ctx, s]) => [
              ctx,
              { ...s },
            ]),
          ),
          createdAt: now,
          updatedAt: now,
        },
      })
    } else if (classId.startsWith(FRAMEWORK_ID_PREFIX)) {
      // Framework class — reuse if id matches; else try by name; else drop.
      if (targetClasses[classId]) {
        plans.set(classId, { kind: 'reuse', id: classId })
      } else {
        const matchedId = frameworkByName.get(cls.name)
        plans.set(
          classId,
          matchedId
            ? { kind: 'reuse', id: matchedId }
            : { kind: 'drop' },
        )
      }
    } else {
      // Regular class — reuse if id is already in target, else import as-is.
      if (targetClasses[classId]) {
        plans.set(classId, { kind: 'reuse', id: classId })
      } else {
        plans.set(classId, {
          kind: 'add',
          id: classId,
          cls: {
            ...cls,
            styles: { ...cls.styles },
            contextStyles: Object.fromEntries(
              Object.entries(cls.contextStyles).map(([ctx, s]) => [
                ctx,
                { ...s },
              ]),
            ),
          },
        })
      }
    }
  }

  // classIdRemap: classes referenced by the subtree but not present in
  // snapshot.classes (e.g. payload was hand-edited) silently fall through —
  // reused if they exist in the target, dropped otherwise.
  const classIdRemap = (classId: string): string | null => {
    const plan = plans.get(classId)
    if (plan) {
      if (plan.kind === 'drop') return null
      return plan.id
    }
    return targetClasses[classId] ? classId : null
  }

  // 1. Materialise added classes into the target site.
  for (const plan of plans.values()) {
    if (plan.kind === 'add' && !site.styleRules[plan.id]) {
      site.styleRules[plan.id] = plan.cls
    }
  }

  // 2. Insert each root's subtree at the resolved location, preserving
  //    snapshot order. For "inside" inserts (target accepts children),
  //    every root is appended; for indexed inserts, each root increments
  //    the insertion index so siblings end up adjacent.
  const newRootIds: string[] = []
  let runningIndex = location.index
  for (const rootId of snapshot.rootNodeIds) {
    const newId = pasteSubtree(
      tree,
      { rootNodeId: rootId, nodes: snapshot.nodes },
      location.parentId,
      runningIndex,
      { nodeIdMap, classIdRemap },
    )
    newRootIds.push(newId)
    if (typeof runningIndex === 'number') runningIndex += 1
  }

  return newRootIds
}
