/**
 * Files Data Layer — type definitions.
 *
 * Architecture source: Contribution #595 §1.2
 *
 * SiteFile is stored as a flat array in site.files (parallel to
 * site.pages). The same flat-map reasoning drives Page.nodes
 * (Decision #309 / Constraint #215).
 *
 * Path invariants are enforced at every write boundary by isSafePath()
 * in pathValidation.ts.
 */

// ---------------------------------------------------------------------------
// SiteFileType
// ---------------------------------------------------------------------------

export type SiteFileType =
  | 'component' // src/components/*.tsx — user-authored React components
  | 'script'    // src/scripts/*.ts, src/utils/*.ts, src/hooks/*.ts
  | 'style'     // src/styles/*.css — global CSS
  | 'asset'     // public/* — images, fonts, etc. (binary)
  | 'config'    // package.json, tsconfig.json, vite.config.ts, .env, etc.
  | 'doc'       // README.md, CHANGELOG.md — markdown docs

// ---------------------------------------------------------------------------
// SiteFile
// ---------------------------------------------------------------------------

export interface SiteFile {
  /** Unique ID — generated with nanoid() (NOT path; path is mutable on rename) */
  id: string

  /**
   * POSIX-style path relative to site root.
   * Examples: "src/components/MyButton.tsx", "public/logo.png", "package.json"
   * Validated by isSafePath() at every write boundary.
   * Must be unique within site.files[].
   */
  path: string

  type: SiteFileType

  /**
   * Text content for component/script/style/config/doc (UTF-8).
   * For 'asset' files this is undefined; binary content lives in `blob`.
   */
  content?: string

  /**
   * For legacy site asset files only — base64-encoded for document persistence.
   * (Blob inside SiteDocument would defeat structuredClone equality checks.)
   */
  blob?: { mimeType: string; base64: string }

  /**
   * When true, the file was auto-generated by the scaffold (e.g. package.json,
   * vite.config.ts, src/main.tsx).  Generated files are read-only in the UI
   * until the user "ejects" them (sets ejected: true).
   *
   * Generated files are hidden from normal authoring UI until ejected.
   */
  generated?: boolean

  /**
   * When true, the user has edited a previously-generated file.
   * Only meaningful when `generated === true`.
   */
  ejected?: boolean

  createdAt: number
  updatedAt: number
}
