/**
 * Clipboard slice — copy/cut/paste for layer subtrees.
 *
 * The clipboard is GLOBAL (not per-site): copying a node in one site can be
 * pasted into another. That makes the slice the single owner of the
 * `pb-clipboard-v1` localStorage key — every read/write goes through this
 * slice. The persisted shape is validated via TypeBox (`ClipboardPayloadSchema`)
 * on load; corruption silently resolves to "no clipboard" rather than throwing.
 *
 * Paste placement is "smart": if the right-clicked target accepts children,
 * the subtree is pasted as the last child of the target; otherwise it is
 * pasted as the next sibling under the target's parent. The page root is
 * always treated as a container.
 *
 * Cross-site paste rules:
 * - Framework classes (`framework:*`) are matched by NAME against the target
 *   site's class registry; if no match exists, the classId is dropped.
 *   Framework classes are deterministically generated by the target site, so
 *   importing the source-side definitions would pollute the target.
 * - Scoped (module-style) classes are always cloned with a fresh ID and the
 *   `scope.nodeId` remapped to the new node ID; scopes referencing nodes
 *   outside the copied subtree are dropped.
 * - All other (regular) classes are imported into the target site preserving
 *   their original ID. Same-ID classes already in the target are reused.
 */

import { nanoid } from 'nanoid'
import type { CSSClass, Page, PageNode } from '@core/page-tree'
import {
  buildSubtreeNodeIdMap,
  getParent,
  pasteSubtree,
} from '@core/page-tree'
import { registry } from '@core/module-engine/registry'
import {
  CLIPBOARD_VERSION,
  type ClipboardPayload,
  clearClipboardPayload,
  readClipboardPayload,
  writeClipboardPayload,
} from '../clipboard/clipboardStorage'
import type { EditorStoreSliceCreator } from '../types'

/**
 * In-memory snapshot of the latest copy/cut. Mirrors the persisted payload
 * but is also kept reactively on the store so menus / shortcuts can react
 * to clipboard changes without polling localStorage.
 */
export interface ClipboardEntry {
  rootNodeId: string
  nodes: Record<string, PageNode>
  classes: Record<string, CSSClass>
  copiedAt: number
}

export interface ClipboardSlice {
  /** Latest copied / cut subtree. Null when the clipboard is empty. */
  clipboardEntry: ClipboardEntry | null

  /** Capture a node's subtree into the clipboard (in memory + localStorage). */
  copyNode: (nodeId: string) => boolean
  /**
   * Copy a node's subtree, then delete it from the active page.
   * Returns true if a copy + delete actually happened.
   */
  cutNode: (nodeId: string) => boolean
  /**
   * Paste the clipboard subtree relative to `targetNodeId`.
   * If the target accepts children, the subtree is appended inside it;
   * otherwise it's inserted as the next sibling under the target's parent.
   * Returns the new root node ID, or null if paste was a no-op.
   */
  pasteNode: (targetNodeId: string) => string | null

  /** Clear the clipboard from memory + localStorage. */
  clearClipboard: () => void
}

declare module '@core/editor-store/types' {
  // Surface this slice's fields on the combined EditorStore type.
  interface EditorStore extends ClipboardSlice {}
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Find the active Page document on the store, ignoring VC mode. */
function getActivePage(state: {
  site: { pages: Page[] } | null
  activePageId: string | null
}): Page | null {
  if (!state.site || !state.activePageId) return null
  return state.site.pages.find((p) => p.id === state.activePageId) ?? null
}

/**
 * Collect the subtree rooted at `nodeId` into a flat nodes map, ready to
 * embed in a clipboard payload. Rejects nodes that are missing from the
 * page tree.
 */
function collectSubtree(
  page: Page,
  nodeId: string,
): { rootNodeId: string; nodes: Record<string, PageNode> } | null {
  if (!page.nodes[nodeId]) return null
  const nodes: Record<string, PageNode> = {}
  const stack = [nodeId]
  while (stack.length > 0) {
    const id = stack.pop()!
    if (nodes[id]) continue
    const node = page.nodes[id]
    if (!node) continue
    nodes[id] = { ...node, children: [...node.children] }
    stack.push(...node.children)
  }
  return { rootNodeId: nodeId, nodes }
}

/**
 * Collect every class referenced anywhere in the subtree from `siteClasses`.
 * Missing classes (e.g. dangling classIds) are silently skipped — the paste
 * step also filters dangling references via the classIdRemap.
 */
function collectReferencedClasses(
  nodes: Record<string, PageNode>,
  siteClasses: Record<string, CSSClass>,
): Record<string, CSSClass> {
  const classes: Record<string, CSSClass> = {}
  for (const node of Object.values(nodes)) {
    for (const classId of node.classIds) {
      if (classes[classId]) continue
      const cls = siteClasses[classId]
      if (cls) classes[classId] = cls
    }
  }
  return classes
}

/**
 * Decide where to paste relative to a target node.
 * - If `target` accepts children (or is the page root), paste inside as the last child.
 * - Otherwise, paste as the next sibling under the target's parent.
 * Returns null if the target is invalid for any reason (e.g. orphan node).
 */
function resolvePasteLocation(
  page: Page,
  targetNodeId: string,
): { parentId: string; index: number | undefined } | null {
  const target = page.nodes[targetNodeId]
  if (!target) return null

  // The page root always accepts children; module registry may or may not have
  // an entry for it depending on registration order. Treat root as a container.
  const isRoot = page.rootNodeId === targetNodeId
  const definition = registry.get(target.moduleId)
  const acceptsChildren = isRoot || definition?.canHaveChildren === true

  if (acceptsChildren) {
    return { parentId: targetNodeId, index: undefined }
  }

  const parent = getParent(page, targetNodeId)
  if (!parent) return null
  const idx = parent.children.indexOf(targetNodeId)
  return { parentId: parent.id, index: idx >= 0 ? idx + 1 : undefined }
}

const FRAMEWORK_ID_PREFIX = 'framework:'

// ---------------------------------------------------------------------------
// Slice implementation
// ---------------------------------------------------------------------------

export const createClipboardSlice: EditorStoreSliceCreator<ClipboardSlice> = (
  set,
  get,
) => {
  // Hydrate the in-memory entry from localStorage at slice creation. The
  // store is built once per session, so this runs at editor mount only.
  const persisted = readClipboardPayload()
  const initialEntry: ClipboardEntry | null = persisted
    ? {
        rootNodeId: persisted.rootNodeId,
        nodes: persisted.nodes,
        classes: persisted.classes,
        copiedAt: persisted.copiedAt,
      }
    : null

  function persistEntry(entry: ClipboardEntry): void {
    const payload: ClipboardPayload = {
      version: CLIPBOARD_VERSION,
      rootNodeId: entry.rootNodeId,
      nodes: entry.nodes,
      classes: entry.classes,
      copiedAt: entry.copiedAt,
    }
    writeClipboardPayload(payload)
  }

  return {
    clipboardEntry: initialEntry,

    copyNode: (nodeId) => {
      const state = get()
      const page = getActivePage(state)
      if (!page) return false
      const subtree = collectSubtree(page, nodeId)
      if (!subtree) return false
      // Refuse to copy the page root — duplicating "the entire page body" has
      // no meaningful target placement and matches the existing duplicate /
      // delete root-guard policy in page-tree mutations.
      if (subtree.rootNodeId === page.rootNodeId) return false

      const siteClasses = state.site?.classes ?? {}
      const classes = collectReferencedClasses(subtree.nodes, siteClasses)
      const entry: ClipboardEntry = {
        rootNodeId: subtree.rootNodeId,
        nodes: subtree.nodes,
        classes,
        copiedAt: Date.now(),
      }
      set({ clipboardEntry: entry })
      persistEntry(entry)
      return true
    },

    cutNode: (nodeId) => {
      const state = get()
      const page = getActivePage(state)
      if (!page) return false
      if (page.rootNodeId === nodeId) return false

      // Copy first; if copy fails (orphan node), don't delete.
      if (!state.copyNode(nodeId)) return false
      // Reuse the existing deleteNode action so undo history + selection
      // behave identically to a manual delete.
      get().deleteNode(nodeId)
      return true
    },

    pasteNode: (targetNodeId) => {
      const state = get()
      const entry = state.clipboardEntry
      if (!entry) return null

      const page = getActivePage(state)
      if (!page) return null
      const location = resolvePasteLocation(page, targetNodeId)
      if (!location) return null

      // Pre-compute new node IDs so scoped-class scope.nodeId can be remapped
      // before classes are written into the target site.
      const nodeIdMap = buildSubtreeNodeIdMap(entry.rootNodeId, entry.nodes)

      // Build the class plan. Each entry resolves to one of:
      //   - { kind: 'reuse', id }   — already present in target site
      //   - { kind: 'add', cls }    — write `cls` to site.classes (id may differ)
      //   - { kind: 'drop' }        — strip from pasted classIds
      type ClassPlan =
        | { kind: 'reuse'; id: string }
        | { kind: 'add'; id: string; cls: CSSClass }
        | { kind: 'drop' }

      const targetSite = state.site
      if (!targetSite) return null

      const now = Date.now()
      const targetClasses = targetSite.classes
      const plans = new Map<string, ClassPlan>()

      // Build a name → id index for framework classes in the target site (used
      // to match framework references that might have a different id across sites).
      const frameworkByName = new Map<string, string>()
      for (const [id, cls] of Object.entries(targetClasses)) {
        if (id.startsWith(FRAMEWORK_ID_PREFIX)) frameworkByName.set(cls.name, id)
      }

      for (const [classId, cls] of Object.entries(entry.classes)) {
        if (cls.scope?.type === 'node') {
          // Scoped class — always cloned with a fresh id, scope.nodeId remapped.
          const newScopeNodeId = nodeIdMap.get(cls.scope.nodeId)
          if (!newScopeNodeId) {
            plans.set(classId, { kind: 'drop' })
            continue
          }
          const newId = nanoid()
          plans.set(classId, {
            kind: 'add',
            id: newId,
            cls: {
              ...cls,
              id: newId,
              scope: { ...cls.scope, nodeId: newScopeNodeId },
              styles: { ...cls.styles },
              breakpointStyles: Object.fromEntries(
                Object.entries(cls.breakpointStyles).map(([bp, s]) => [
                  bp,
                  { ...s },
                ]),
              ),
              createdAt: now,
              updatedAt: now,
            },
          })
        } else if (classId.startsWith(FRAMEWORK_ID_PREFIX)) {
          // Framework class — reuse if id matches; else try by name; else drop.
          if (targetClasses[classId]) {
            plans.set(classId, { kind: 'reuse', id: classId })
          } else {
            const matchedId = frameworkByName.get(cls.name)
            plans.set(
              classId,
              matchedId
                ? { kind: 'reuse', id: matchedId }
                : { kind: 'drop' },
            )
          }
        } else {
          // Regular class — reuse if id is already in target, else import as-is.
          if (targetClasses[classId]) {
            plans.set(classId, { kind: 'reuse', id: classId })
          } else {
            plans.set(classId, {
              kind: 'add',
              id: classId,
              cls: {
                ...cls,
                styles: { ...cls.styles },
                breakpointStyles: Object.fromEntries(
                  Object.entries(cls.breakpointStyles).map(([bp, s]) => [
                    bp,
                    { ...s },
                  ]),
                ),
              },
            })
          }
        }
      }

      // classIdRemap: classes referenced by the subtree but not present in
      // entry.classes (e.g. payload was hand-edited) silently fall through —
      // reused if they exist in the target, dropped otherwise.
      const classIdRemap = (classId: string): string | null => {
        const plan = plans.get(classId)
        if (plan) {
          if (plan.kind === 'drop') return null
          return plan.id
        }
        return targetClasses[classId] ? classId : null
      }

      // Snapshot history once; the entire paste is a single undo step.
      get().pushHistory()
      let newRootId: string | null = null
      set((draft) => {
        if (!draft.site) return
        const draftPage = draft.site.pages.find((p) => p.id === draft.activePageId)
        if (!draftPage) return

        // 1. Materialise added classes into the target site.
        for (const plan of plans.values()) {
          if (plan.kind === 'add' && !draft.site.classes[plan.id]) {
            draft.site.classes[plan.id] = plan.cls
          }
        }

        // 2. Insert the subtree using the precomputed nodeIdMap so scoped
        //    classes already point at the new IDs.
        newRootId = pasteSubtree(
          draftPage,
          { rootNodeId: entry.rootNodeId, nodes: entry.nodes },
          location.parentId,
          location.index,
          { nodeIdMap, classIdRemap },
        )

        draft.site.updatedAt = Date.now()
        draft.hasUnsavedChanges = true
      })

      return newRootId
    },

    clearClipboard: () => {
      set({ clipboardEntry: null })
      clearClipboardPayload()
    },
  }
}
